services:
  - type: web
    name: bloodconnect-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://siddheshwarharshad_db_:a13O7bEtdfmRNSqk@cluster0.hyoa8sj.mongodb.net/bloodconnect?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: bloodconnect_super_secret_key_12345
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
    healthCheckPath: /
